# Site settings
title: Nick Codes
email: nick@nick.codes
mobile: 650.704.4969
description: > # this means to ignore newlines until "baseurl:"
  Teaching you to write code that doesn't suck.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nick.codes" # the base hostname & protocol for your site
linkedin_username: nickpalmer
twitter_username: nick_codes
github_username:  nick-codes

paginate: 10
paginate_path: "/posts/page:num/"
permalink: /posts/:title

# Build settings
markdown: kramdown

jekyll-archives:
#  enabled: all
#  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
